### ISSUE TITLE
indirmelerde sorun

### ISSUE THREAD

**Issue by rosso06** [cangokceaslan/applicationarize#1]
Merhaba mevcut web sitesinde indirme foksiyonu çalışmıyor. Örneğin web sitede bir içeriği indirmek için butona bastığımızda içerik inmiyor.

**Comment by cangokceaslan** [comment]
Merhabalar,

electron-dl modülündeki 
```json
{
     "saveAs":true
}
``` 
parametre olarak eklendi. 

0.0.20 sürümünü indirip tekrar deneyebilirsin

Kolaylıklar
